### ISSUE TITLE
ERROR: could not access file "$libdir/postgis-2.2": No such file or directory while tabulating

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/layers-store#3]
The following errors occur while tabulating:

```
2016-12-06 00:21:33,523 FieldDAOImpl Getting enabled field info for id = cl1058
2016-12-06 00:21:33,525 FieldController field id: cl1058
2016-12-06 00:21:33,525 ObjectDAOImpl Getting object info for fid = cl1058
2016-12-06 00:21:33,533 GrailsExceptionResolver PSQLException occurred when processing request: [GET] /spatial-service/field/cl1058
ERROR: could not access file "$libdir/postgis-2.2": No such file or directory. Stacktrace follows:
org.postgresql.util.PSQLException: ERROR: could not access file "$libdir/postgis-2.2": No such file or directory
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2161)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1890)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:559)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:417)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeQuery(AbstractJdbc2Statement.java:302)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:76)
	at au.org.ala.layers.dao.ObjectDAOImpl.getObjectsById(ObjectDAOImpl.java:200)
	at au.org.ala.layers.FieldController.show(FieldController.groovy:69)
	at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
	at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
	at au.org.ala.cas.client.UriFilter.doFilter(UriFilter.java:200)
	at au.org.ala.cas.client.UriFilter.doFilter(UriFilter.java:200)
	at au.org.ala.cas.client.UriFilter.doFilter(UriFilter.java:200)
	at org.jasig.cas.client.session.SingleSignOutFilter.doFilter(SingleSignOutFilter.java:65)
	at com.brandseye.cors.CorsFilter.doFilter(CorsFilter.java:82)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
2016-12-06 00:21:33,561 FieldDAOImpl Getting enabled field info for id = cl20
2016-12-06 00:21:33,562 FieldController field id: cl20
2016-12-06 00:21:33,562 ObjectDAOImpl Getting object info for fid = cl20
2016-12-06 00:21:33,571 GrailsExceptionResolver PSQLException occurred when processing request: [GET] /spatial-service/field/cl20
ERROR: could not access file "$libdir/postgis-2.2": No such file or directory. Stacktrace follows:
org.postgresql.util.PSQLException: ERROR: could not access file "$libdir/postgis-2.2": No such file or directory
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2161)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1890)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:559)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:417)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeQuery(AbstractJdbc2Statement.java:302)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:76)
	at au.org.ala.layers.dao.ObjectDAOImpl.getObjectsById(ObjectDAOImpl.java:200)
	at au.org.ala.layers.FieldController.show(FieldController.groovy:69)
	at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
	at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
	at au.org.ala.cas.client.UriFilter.doFilter(UriFilter.java:200)
	at au.org.ala.cas.client.UriFilter.doFilter(UriFilter.java:200)
	at au.org.ala.cas.client.UriFilter.doFilter(UriFilter.java:200)
	at org.jasig.cas.client.session.SingleSignOutFilter.doFilter(SingleSignOutFilter.java:65)
	at com.brandseye.cors.CorsFilter.doFilter(CorsFilter.java:82)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
2016-12-06 00:21:33,622 TaskService$TaskThread error running request: 368886
groovy.lang.MissingPropertyException: No such property: err for class: au.org.ala.spatial.slave.Task
Possible solutions: id
	at au.org.ala.spatial.process.TabulationCreateOne.start(TabulationCreateOne.groovy:85)
	at au.org.ala.spatial.slave.TaskService$TaskThread.run(TaskService.groovy:288)
2016-12-06 00:21:33,636 TaskService$TaskThread about to remove running task
```

**Comment by ansell** [comment]
Possibly useful stackoverflow question for this:

https://stackoverflow.com/questions/36444577/postgresql-cant-access-to-file-libdir-postgis-2-1-no-such-file-or-directo

**Comment by jasp255** [comment]
The instalator from BigSQL site not work.
The solution is download the instalator from this site:
https://www.enterprisedb.com/downloads/postgres-postgresql-downloads

**Comment by Hiram2018** [comment]
You have to reinstall postgis from yum install, these wotks for me...
